FROM alpine:3.20.0 as base

ARG MAINTAINER
ARG VERSION
ARG PROJECT_NAME

LABEL DCU_MAINTAINER="${MAINTAINER}"
LABEL DCU_PROJECT_NAME="${PROJECT_NAME}"
LABEL DCU_VERSION="${VERSION}"

ENV DCU_MAINTAINER="${MAINTAINER}"
ENV DCU_PROJECT_NAME="${PROJECT_NAME}"
ENV DCU_VERSION="${VERSION}"

RUN apk update && \
apk add \
    bash \
    coreutils \
    curl \
    docker \
    gawk \
    grep \
    jq \
    ncurses \
    postfix \
    unzip \
    wget \
    which \
    zip \
&& rm -rf /var/cache/apk/* 

WORKDIR /opt/dcu
COPY ./LICENSE /opt/dcu/LICENSE
COPY ./entrypoint.sh /opt/dcu/entrypoint.sh
COPY ./dcu.sh /opt/dcu/dcu.sh
RUN chmod ugo+x dcu_main.sh entrypoint.sh

ENTRYPOINT [ "/opt/dcu/entrypoint.sh" ]
